baseURL = 'https://sarsoo.xyz/'
languageCode = 'en-gb'
title = 'sarsoo.xyz'
theme = 'hugo-coder'

paginate = 40

[taxonomies]
  category = 'categories'
  tag = 'tags'
  art = 'art'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "sarsoo"
  info = "dev & engineering"
  description = "sarsoo dev & engineering portfolio"
  since = "2019"
  keywords = "dev,engineering"
  avatarurl = "images/avatar.jpg"
  hideColorSchemeToggle = true

[[params.social]]
  name = "Mastodon"
  icon = "fa fa-mastodon fa-2x"
  weight = 1
  url = "https://fosstodon.org/@sarsoo/"
[[params.social]]
  name = "Instagram"
  icon = "fa fa-instagram fa-2x"
  weight = 2
  url = "https://www.instagram.com/pack_it_in_/"
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 3
  url = "https://github.com/sarsoo/"
[[params.social]]
  name = "Last.fm"
  icon = "fa fa-lastfm fa-2x"
  weight = 4
  url = "https://last.fm/user/sarsoo/"
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 5
  url = "https://www.linkedin.com/in/andypack/"

[[menu.main]]
  name = "Mixonomer"
  weight = 1
  url  = "mixonomer/"

[[menu.main]]
  name = "Dev & Engineering"
  weight = 2
  url  = "dev-engineering/"

[[menu.main]]
  name = "Music"
  weight = 3
  url  = "music/"

#[[menu.main]]
#  name = "Art"
#  weight = 4
#  url  = "art/"

[[menu.main]]
  name = "Posts"
  weight = 5
  url  = "posts/"

[[menu.main]]
  name = "About"
  weight = 6
  url  = "about/"