name: Deploy Hugo site to Prod

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build Container
    steps:
      - uses: actions/checkout@v4
        with: 
          github-server-url: https://gitea.sheep-ghoul.ts.net

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: gitea.sheep-ghoul.ts.net
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Container
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gitea.sheep-ghoul.ts.net/sarsoo/sarsooxyz.hugo:latest
          file: Dockerfile.pub
